### ISSUE TITLE
Rev Collector longer collects revs by default if using gulp-rev 4.0

### ISSUE THREAD

**Issue by tony2nite** [shonny-ua/gulp-rev-collector#13]
In gulp-rev 4.0 the new [default hash length is now 10]
(https://github.com/sindresorhus/gulp-rev/commit/11e859ee78aa48b0a2cbb23b1c705df7616ffbd4) so the default ```revSuffix``` value no longer picks up the manifest hash.

Setting the revSuffix config correctly to allow for 10 character makes it work again:
```
revSuffix: '-[0-9a-f]{10}-?'
```

Not an issue with Rev Collector as such, but added here for the record.

**Comment by shonny-ua** [comment]
Use version 1.0.0 and have fun! ;)

**Comment by tony2nite** [comment]
👍
