### ISSUE TITLE
dirReplacements not working properly

### ISSUE THREAD

**Issue by dciccale** [shonny-ua/gulp-rev-collector#17]
`rev-manifest.json`
```json
{
  "assets/images/avatar.png": "assets/images/avatar-616d026e5f.png"
}
```

`gulpfile.js`
```js
...
gulp.task('rev-img', ['imagemin'], function () {
  return gulp.src(['rev-manifest.json', 'dist/server/views/index.jade'])
    .pipe($.revCollector({
      replaceReved: true,
      dirReplacements: {
        'assets/images/': 'http://my.cdn.net/'
      }
    }))
    .pipe(gulp.dest('dist/server/views'));
});
```

`dist/server/views/index.jade`
```jade
p
  img.img-responsive(src="/assets/images/avatar.png")
```

it doesn't get replaced.

desired output:

```jade
p
  img.img-responsive(src="http://my.cdn.net/avatar-616d026e5f.png")
```

i am not sure i am using `dirReplacements` correctly.

what i don't see clear is why you are concatenating the replacement string with the pattern at line 93 https://github.com/shonny-ua/gulp-rev-collector/blob/master/index.js#L93

that makes the `regexp` to be `/assets\/images\/assets\/images\/avatar\.png/g`

**Comment by dciccale** [comment]
i made workaround:

```js
      dirReplacements: {
        // 'assets/images': 'http://my.cdn.net/'
        '/': function (file) {
          return file.replace(/assets\/images\//, 'http://my.cdn.net/');
        }
      }
```

however would be cool just using the `dirReplacements` mappping

**Comment by shonny-ua** [comment]
dirReplacements works "outside" to rev-manifest patterns.

If You  have next rev-manifest.json:
```
{
  "avatar.png": "avatar-616d026e5f.png"
}
```
next revCollector option
```
      dirReplacements: {
        '/assets/images/': 'http://my.cdn.net/'
      }
```
will work correctly.

For other cases using function as value of dirReplacements object was added.
