### ISSUE TITLE
replaceReved won't work while a link is end with string such as '.min.js' 

### ISSUE THREAD

**Issue by wzshuang** [shonny-ua/gulp-rev-collector#18]
It works well first time, but won't replace alredy replaced links.

![github](https://cloud.githubusercontent.com/assets/8585771/10447985/fc4cf9f8-71bb-11e5-810d-259285b7dd9a.png)
![github2](https://cloud.githubusercontent.com/assets/8585771/10448020/5be3e214-71bc-11e5-89a7-26f276fc83e7.png)
![github3](https://cloud.githubusercontent.com/assets/8585771/10448021/60810acc-71bc-11e5-85b9-635408a3880b.png)

**Comment by shonny-ua** [comment]
You can use 'revSuffix' option to achieve the goal.
try:
```
...
    .pipe( revCollector({
            replaceReved: true,
            revSuffix: '-[0-9a-f]{8,10}-?(\.min)?'
...
```
I do not remember exactly how 'gulp-rev' handles  files with suffix '.min'.
Probably, You need to use revSuffix: '(\.min)?-[0-9a-f]{8,10}-?'

**Comment by wzshuang** [comment]
thanks, I'll try it later.
