### ISSUE TITLE
use with other manifest files not generated by gulp-rev

### ISSUE THREAD

**Issue by tehandyb** [shonny-ua/gulp-rev-collector#19]
Is it possible to use this plugin with generic manifest files? It seems that the plugin only works with manifest files that have revved assets generated from gulp-rev. But if I have a webpack asset manifest, or just a generic asset manifest created with another tool, the manifest file does not work with gulp-rev-collector.

**Comment by shonny-ua** [comment]
All is possible, if time to do it is available. I don't use webpack or other generic assets tools. Please, describe the problems You are to face more. I'll see what I can do.
