### ISSUE TITLE
Breaks for multi-constant concatenation?

### ISSUE THREAD

**Issue by momoadeli** [shonny-ua/gulp-rev-collector#23]
rev-collector fails when I use two constants to build an image path to 'testdefault.png'
(testdefault-XXXXXXX.png is NOT created):

`URLS = {
      IMAGE_PREFIX:"",
IMAGE_BASE_LOCAL_CAST_BANNERS:"img/banners"}

DEFAULT_IMAGE = {
    TEST: 
{TESTDEFAULT:cf.URLS.IMAGE_PREFIX + URLS.IMAGE_BASE_LOCAL_CAST_BANNERS+ "/testdefault.png"
}
`
However, once I remove the second constant and define the path a little more explicitly, rev-collect works (testdefault-XXXXXXX.png is created):

DEFAULT_IMAGE = {
    TEST: 
{
TESTDEFAULT:cf.URLS.IMAGE_PREFIX +  "img/banners/testdefault.png"
}
`
manifest is correct:
"img/banners/testdefault.png": "img/banners/testdefault-13626465c2.png"

Please advise.

Many Thanks!

**Comment by shonny-ua** [comment]
Hmmm... The rev-collector don't generate any manifest files. It's work for gulp-rev.

This module collect different generated manifests, and makes necessary replacements in html template.
