### ISSUE TITLE
replace twice issue

### ISSUE THREAD

**Issue by lanyongly** [shonny-ua/gulp-rev-collector#25]
Hi
 
I have a ‘replace twice’ issue about gulp-rev-collector 
 
When I execute the build, the keys to replace will be create in rev-manifest.json
 
The keys is below:
"22.png": "22-b0af3e9bd6.png",
"active/04/0402.png": "active/04/0402-88b7b2fb22.png",
 
After that, use the keys to replace, and the issue will be happened.
 
22.png is OK.
Problem is 0402.png.
 
I think the file name ‘0402.png’ will be replaced to ‘0402-88b7b2fb22.png’ at first time.
Then, ‘0402-88b7b2fb22.png’ will be replaced to ‘0402-88b7b2fb22-b0af3e9bd6.png’ at twice.
 
It make the picture with wrong file name can not display on the web page.
 
Please fix the issue.
 
Best Regards!

**Comment by shonny-ua** [comment]
use version 1.0.4 and have fun!

**Comment by lanyongly** [comment]
Thanks for  fix . great job
