### ISSUE TITLE
why not support node v6.2.1

### ISSUE THREAD

**Issue by trojanliu** [shonny-ua/gulp-rev-collector#26]
why not support node v6.2.1

**Comment by trojanliu** [comment]
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received [ { type: 'FragmentView',

**Comment by shonny-ua** [comment]
WTF?
gulp-rev-collector don't containts files like "text!../../templates/common/serviceTemp.json"...
Please describe the problem expanded.

**Comment by trojanliu** [comment]
gulp.task 'md5_replace_static' , ->
    return gulp.src [
        'images/rev-manifest.json',
        'static/runtime/js/*'
    ]
    .pipe(revCollector())
    .pipe(gulp.dest('static/runtime/js'))
    .on 'end', ->
        if fs.existsSync 'static/runtime/js/rev-manifest.json'

if my js file contain like "text!../../templates/common/serviceTemp.json" that is a json file, it would be wrong.

**Comment by shonny-ua** [comment]
what is contained in images/rev-manifest.json?

**Comment by shonny-ua** [comment]
Try to use v 1.0.5
