### ISSUE TITLE
when I modified the rev_manifest.json ..

### ISSUE THREAD

**Issue by trickyEdecay** [shonny-ua/gulp-rev-collector#30]
I used some methods to modify the **rev_manifest.json** after use gulp-rev

and now , my **rev_manifest.json** looks like this:
```
{
  "assets/less/common.less": "assets/css/common-2c0d21e40c.css"
}
```

**It means that they have different ext : less & css**

and I found that was cause by the **index.js** on **line  31**
```
if ( !_.isString(json[key]) || path.basename(json[key]).replace(new RegExp( opts.revSuffix ), '' ) !==  path.basename(key) ) {
```

could u delete the second condition for this issue? or there may cause more issues?

**Comment by shonny-ua** [comment]
Use version 1.2.0
