### ISSUE TITLE
About the replace part when using the manifest

### ISSUE THREAD

**Issue by mathxlee** [shonny-ua/gulp-rev-collector#31]
Well, there is another situation which is the content between the brackets in css url is not always have quotes, like `background: url(/img/static.jpg)`, and this is legal, but when this situation, the replace part when you are using the manifest, it won't work.

**Comment by thinkswan** [comment]
This has been fixed in #29 by @dingyi1993, but it still needs to be merged. @shonny-ua, any chance you'll be able to take a look at that PR at some point? 😄

**Comment by thinkswan** [comment]
This has been fixed in #37.

**Comment by shonny-ua** [comment]
Use version 1.2.0
