### ISSUE TITLE
gulp-rev-collector fails to recognize `.js.map` entries, and rejects therefore the entire `rev-manifest.json`

### ISSUE THREAD

**Issue by Ocramius** [shonny-ua/gulp-rev-collector#33]
Possibly related to https://github.com/shonny-ua/gulp-rev-collector/issues/30

[This condition](https://github.com/shonny-ua/gulp-rev-collector/blob/4fcf067f1e75e2afc5cf56571484d584589e62cf/index.js#L31) will fail to recognize a `rev-manifest.json` such as following:

```json
{
    "js/app.js": "js/app-aaaaaaaaaa.js",
    "maps/js/app.js.map": "maps/js/app-aaaaaaaaaa.js.map"
}
```

The reason is the last conditional, which will compare `app.js.map` and `app.js` (`path.basename('app-aaaaaaaaaa.js.map')` is `'app-aaaaaaaaaa.js'`

Writing a test as I'm reporting this.

**Comment by shonny-ua** [comment]
This test passed.On a linux system. It's only windows problem?

**Comment by Ocramius** [comment]
@shonny-ua the setup is more complex, as it's a mix of vagrant/windows/linux.

As far as I'm concerned, since I'm no longer working on that project, and no longer have access to that specific environment, this is an unsolved issue, but I won't be able to look further into it.

To people getting to this issue after a lot of searching, I can only suggest to get a proper dev/prod environment, and stop building stuff on windows: you are actively hurting yourselves.

The resolution of this issue is `incomplete`.
