### ISSUE TITLE
replacement of the asset name like 'none-d56725a517-d56725a517.png', cannot replace with the manifest.json

### ISSUE THREAD

**Issue by lmx99** [shonny-ua/gulp-rev-collector#47]
the bellow we would see is part of the index.js codes of gulp-rev-collector
```
 var cleanReplacement = path.basename(json[key]).replace(new RegExp(opts.revSuffix), '');

                if (!~[
                        path.basename(key),
                        _mapExtnames(path.basename(key), opts)
                    ].indexOf(cleanReplacement)) {
                    isRev = 0;
                }
```
when my source file path look like **none-d56725a517-d56725a517.png** ,  the result path of the replacement via `var cleanReplacement = path.basename(json[key]).replace(new RegExp(opts.revSuffix), '');` will be the string like **noned56725a517.png**, the right way of this result should be **none-d56725a517.png** .  for the issue  the revcollect cannot work as we expected

**Comment by shonny-ua** [comment]
use option ```revSuffix: '-[0-9a-f]{8,10}'``` to resolve your task
