### ISSUE TITLE
it doesn't replace dependency

### ISSUE THREAD

**Issue by mariodeci** [shonny-ua/gulp-rev-collector#50]
I'm using TS with import, for example in app.module.ts I have:
import {CheckedDirective} from "./common/directives/checked.directive";

checked.directive is a TS in that directory.

With gulp-rev, after tsc, it is correctly revisioned as:  checked-0a90e14b3d.directive.js
and inserted in manifest
  "app/common/directives/checked.directive.js": "app/common/directives/checked-0a90e14b3d.directive.js",

gulp-rev-collector doesn't rewrite the dependency in "app/app-c3170cc5cd.module.js", it remains:
var checked_directive_1 = require("./common/directives/checked.directive");

What can I do?
My gulp tasks:

`gulp.task('revision:rename', () =>
    gulp.src([
        BUILD_DIR+"/**/*.html",
        BUILD_DIR+"/**/*.css",
        BUILD_DIR+"/**/*.js",
        "!"+BUILD_DIR+"/index.html",
        "!"+BUILD_DIR+"/favicon.ico",
        BUILD_DIR+"/**/*.{jpg,png,jpeg,gif,svg,ico,PNG}"])
        .pipe(rev())
             .pipe(gulp.dest(DIST_ASSEMBLE))
                .pipe(rev.manifest({ path: 'manifest.json' }))
                 .pipe(gulp.dest(DIST_ASSEMBLE))
);

**//update references in js but not rewrite 
//import {CheckedDirective} from "./common/directives/checked.directive";
//in import {CheckedDirective} from "./common/directives/checked-0a90e14b3d.directive";**
gulp.task("revision:updateReferences", () =>
    gulp.src([DIST_ASSEMBLE+"/manifest.json","distassemble/**/*.{html,json,css,js}"])
        .pipe(collect())
        .pipe(gulp.dest(DIST_ASSEMBLE))
);`

**Comment by shonny-ua** [comment]
You car reach the result:
1. using gulp-rev-collector v1.3.0
2. change your manifest to 
```
"common/directives/checked.directive.js": "common/directives/checked-0a90e14b3d.directive.js",
```
or change require call to
```
var checked_directive_1 = require("../app/common/directives/checked.directive");
```
3. using ```extMap``` option for  gulp-rev-collector like:
```
var revCollector = require('gulp-rev-collector');
...
.pipe( revCollector({
            extMap: {
                '.directive.js': '.directive'
            }
}) )
...
```

**Comment by mariodeci** [comment]
Thanks for your response but:
manifest is already generated as you write:
`"common/directives/checked.directive.js": "common/directives/checked-0a90e14b3d.directive.js",`

Also I can't change require call (you leave it like I wrote, I don't understand the difference)
`var checked_directive_1 = require("../app/common/directives/checked.directive");`
cause all js are automatically generated from typescript with TSC (gulp previous task).
The chain is: program in TS --> gulp tsc to automatically obtain .js that I don't change --> gulp rev + gulp collector  

With `extMap` I must write all dependeces manually?

**Comment by shonny-ua** [comment]
1. yes! my module cant find pattern ```app/common/directives/checked.directive``` in string ```./common/directives/checked.directive``` to replacement. without serios rewrite it can`t.
you can modify content of your manifests before using collector.
ETC:
```
var through         = require('through2');
through

function replacer() {
    return through.obj(function(file, enc, cb){
        if (path.extname(file) === '.json') {
            var src = file.contents.toString('utf8');
            src = src.replace(/"app\//g, '/');
            file.contents = new Buffer(src);
        }
        this.push(file);
        cb();
    });
}
...

gulp.task("revision:updateReferences", () =>
gulp.src([DIST_ASSEMBLE+"/manifest.json","distassemble/**/*.{html,json,css,js}"])
.pipe(replacer())
.pipe(collect({extMap: {
                '.directive.js': '.directive',
                '.service.js': '.service',
                '.pipe.js': '.pipe',
                '.module.js': '.module'
            }}))
.pipe(gulp.dest(DIST_ASSEMBLE))
);
```
without 5000 rows modyfy... 
2. if you realise 1, it don't needed.
3. yes. you need rules for ```.directive```, ```..service```, ```.pipe```... what else? ```.module```...
isn't a "lot" variants. copypast them from exsample below...
