### ISSUE TITLE
use version 1.2.2, can't replace with manifes.json

### ISSUE THREAD

**Issue by wwervin72** [shonny-ua/gulp-rev-collector#53]
![image](https://user-images.githubusercontent.com/17847729/49140735-00ab3480-f330-11e8-8c9a-fd31164039ff.png)
![image](https://user-images.githubusercontent.com/17847729/49140757-115baa80-f330-11e8-9be2-6619593fe0b4.png)
![image](https://user-images.githubusercontent.com/17847729/49140764-16b8f500-f330-11e8-85aa-63d964278f8c.png)
![image](https://user-images.githubusercontent.com/17847729/49140849-47009380-f330-11e8-92fc-8b2c645afc6e.png)
i execute rev task, There is no difference between output and source

**Comment by shonny-ua** [comment]
Show me rev-manifest.json file content , please.

**Comment by wwervin72** [comment]
![image](https://user-images.githubusercontent.com/17847729/49206335-b8058100-f3ec-11e8-8aad-6fbdf6c29025.png)

**Comment by wwervin72** [comment]
![image](https://user-images.githubusercontent.com/17847729/49206404-e8e5b600-f3ec-11e8-86b4-73109e579358.png)

**Comment by shonny-ua** [comment]
Need You badly sufix '-min' in file names?
you should do not use it.
or change your index.html content like
```
<script src="./js/main-min.js"></script>
```

**Comment by wwervin72** [comment]
it works, thank you very much
