### ISSUE TITLE
path replace auto bug

### ISSUE THREAD

**Issue by chaochao11** [shonny-ua/gulp-rev-collector#54]
replace fail

**Comment by chaochao11** [comment]
<img width="1052" alt="wechatimg36112" src="https://user-images.githubusercontent.com/25171009/50212186-60d44a00-03b5-11e9-8f58-76cc45c445d1.png">
<img width="1025" alt="wechatimg36111" src="https://user-images.githubusercontent.com/25171009/50212190-629e0d80-03b5-11e9-90ab-fdd48da6d452.png">

**Comment by shonny-ua** [comment]
what fail? 
What did you expect? Explain, please.

**Comment by chaochao11** [comment]
I want to automatically introduce the path when it is correct.
For example: I sent first Photo

**Comment by chaochao11** [comment]
my gulpFile.js
![image](https://user-images.githubusercontent.com/25171009/50275071-8e82c700-0479-11e9-90e5-79d6cf411e87.png)

**Comment by shonny-ua** [comment]
keys in ```dirReplacements``` aren't file extensions. try use something like:
```
dirReplacements: {
    './script': '/dist/script',
    './css': '/dist/css',
    './assets': '/dist/assets'
}
```

**Comment by chaochao11** [comment]
The problem remains

**Comment by shonny-ua** [comment]
What problem& You haven't explain it...
You 'rev' task is depended by 'script' and 'style'?
Like ```gulp.task('rev', [ 'script', 'style'], function () {```...

**Comment by chaochao11** [comment]
According to what you said, the hash of the file introduced by index.html under dist was not added after packaging
![image](https://user-images.githubusercontent.com/25171009/50585559-9185aa80-0eb0-11e9-8f68-acb45109c835.png)
![image](https://user-images.githubusercontent.com/25171009/50585572-a5c9a780-0eb0-11e9-88ce-e40dba77ab94.png)

**Comment by shonny-ua** [comment]
what contain ```rev/css/rev-manifest.json``` and ```rev/script/rev-manifest.json```?

**Comment by shonny-ua** [comment]
I dont known what can i do for you. I wrote next test:
```
'use strict';
var assert              = require('assert');
var Vinyl               = require('vinyl');
var revCollector        = require('./index');
var path                = require('path');
var isEqual             = require('lodash.isequal');

var man1 = '{"index.css": "index-653fc57696.css"}';
var man2 = '{"code.js": "code-1e9c139c3b.js","index.js": "index-845e00e6af.js"}';
var htmlt = '<html><head><link rel="stylesheet" href="./css/index.css" /><script src=./script/code.js></script><script src=./script/index.js></script></head><body><img src="cdn/image.gif" /></body></html>';

it('should', function (cb) {
    var stream = revCollector({
        replaceReved: true,
        dirReplacements:{
            './script': '/dist/script',
            './css': '/dist/css',
            './assets': '/dist/assets'
        }
    });

    stream.write(new Vinyl({
        path: 'rev/css/rev-manifest.json',
        contents: new Buffer(man1)
    }));

    stream.write(new Vinyl({
        path: 'rev/script/rev-manifest.json',
        contents: new Buffer(man2)
    }));

    stream.write(new Vinyl({
        path: 'index.html',
        contents: new Buffer(htmlt)
    }));

    stream.on('data', function (file) {
        var ext = path.extname(file.path);
        var contents = file.contents.toString('utf8');

        console.log(contents);

    });

    stream.on('end', function() {
        cb();
    });

    stream.end();
});
```

all works correctly.

replaced html is next:
```
<html><head><link rel="stylesheet" href="/dist/css/index-653fc57696.css" /><script src=/dist/script/code-1e9c139c3b.js></script><script src=/dist/script/index-845e00e6af.js></script></head><body><img src="cdn/image.gif" /></body></html>
```

I can't detect your mistake using ```gulp-rev-collector```.
