### ISSUE TITLE
Broken through2 dependency

### ISSUE THREAD

**Issue by nickdunn** [shonny-ua/gulp-rev-collector#61]
I use gulp-rev-collector religiously on a lot of projects. I have one where I have on a very limited CI build infrastructure on an old Node version (v0.10.x). The build recently started failing because gul-rev-collector has a very liberal dependency on through2:

    "through2": ">=0.5.1",

About 3 weeks ago https://www.npmjs.com/package/through2 updated with a much newer Node dependency, which is causing my builds to break:

> Note: Users of Node.js 0.10 and 0.12 should install through2@2.x. As of through2@3.x, readable-stream@3 is being used and is not compatible with older versions of Node.js. v2.x support is being maintained on the v2.x branch.

Is there any chance you could publish a new version of gul-rev-collector locked to v2 of through2 for us poor souls stuck on older Node versions that we're not in control of changing?

Thank you!

**Comment by shonny-ua** [comment]
Use version 1.3.2 and have fun!
